version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: awign
      POSTGRES_PASSWORD: awign
      POSTGRES_DB: awigndb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    environment:
      DATABASE_URL: postgresql://awign:awign@db:5432/awigndb
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:

